import React, { useState, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import {
  Search, Plus, Edit, Eye, Trash2, X, Save, CheckCircle2, AlertCircle, Ban, PlayCircle, Lock, Unlock, Grid, List, ChevronLeft, ChevronRight, Sheet, BookOpen
} from 'lucide-react';
import { showToast } from '../../config/toastConfig';
import { StyledSelect } from '../../components/StyledSelect';
import GlassEffect from '../../components/GlassEffect';
import AdminSectionHeader from '../../components/AdminSectionHeader';
import { mapToRedScheme, RedColorPalette } from '../../utils/colorMapper';
import { useBreakpoints } from '../../hooks/useMediaQuery';
import '../../styles/responsive.css';
import '../../utils/modalScrollHelper';

type Course = {
  id_curso: number;
  codigo_curso: string;
  id_tipo_curso: number;
  nombre: string;
  horario: 'matutino' | 'vespertino';
  capacidad_maxima: number;
  cupos_disponibles?: number;
  fecha_inicio: string; // YYYY-MM-DD
  fecha_fin: string; // YYYY-MM-DD
  estado: 'planificado' | 'activo' | 'finalizado' | 'cancelado';
};

type EstadoFilter = 'todos' | Course['estado'];

// Opciones para selects (catálogos)
type TipoCursoOption = {
  id_tipo_curso: number;
  nombre: string;
  estado?: 'activo' | 'inactivo';
  duracion_meses?: number | null;
};

// Eliminado manejo de aulas en esta UI

const API_BASE = (import.meta as any).env?.VITE_API_URL || 'http://localhost:3000';

const GestionCursos = () => {
  const { isMobile, isSmallScreen } = useBreakpoints();
  const [cursos, setCursos] = useState<Course[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedCurso, setSelectedCurso] = useState<Course | null>(null);
  const [modalType, setModalType] = useState<'create' | 'edit' | 'view'>('create');
  const [showModal, setShowModal] = useState(false);
  const [filterEstado, setFilterEstado] = useState<string>('todos');
  const [searchTerm, setSearchTerm] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [selectedTipoCurso, setSelectedTipoCurso] = useState<number | null>(null);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const [tiposCursos, setTiposCursos] = useState<TipoCursoOption[]>([]);
  const [cursoToDelete, setCursoToDelete] = useState<Course | null>(null);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [deletingCurso, setDeletingCurso] = useState(false);

  // Estados para vista y paginación
  const [viewMode, setViewMode] = useState<'cards' | 'table'>('cards');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 8; // 8 cursos por página en tabla

  // Detectar modo oscuro desde localStorage
  const [darkMode, setDarkMode] = useState(() => {
    const saved = localStorage.getItem('admin-dark-mode');
    return saved !== null ? JSON.parse(saved) : true;
  });

  // Escuchar cambios en el modo oscuro
  useEffect(() => {
    const interval = setInterval(() => {
      const saved = localStorage.getItem('admin-dark-mode');
      const newMode = saved !== null ? JSON.parse(saved) : true;
      if (newMode !== darkMode) {
        setDarkMode(newMode);
      }
    }, 100);

    return () => clearInterval(interval);
  }, [darkMode]);

  const themeColors = useMemo(() => ({
    textPrimary: darkMode ? '#f8fafc' : '#1f2937',
    textSecondary: darkMode ? 'rgba(248,250,252,0.75)' : 'rgba(71,85,105,0.85)',
    textMuted: darkMode ? 'rgba(255,255,255,0.6)' : 'rgba(100,116,139,0.85)',
    iconMuted: darkMode ? 'rgba(255,255,255,0.5)' : 'rgba(148,163,184,0.7)',
    controlBg: darkMode ? 'rgba(255,255,255,0.1)' : '#ffffff',
    controlBgSoft: darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(248,250,252,0.9)',
    controlBorder: darkMode ? 'rgba(255,255,255,0.2)' : 'rgba(148,163,184,0.45)',
    sectionSurface: darkMode
      ? 'linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(26,26,26,0.9) 100%)'
      : 'linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(254,242,242,0.95) 100%)',
    sectionBorder: darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(252, 165, 165, 0.45)',
    surfaceHover: darkMode ? 'rgba(248,113,113,0.2)' : 'rgba(252, 165, 165, 0.35)',
    tableHeaderBg: darkMode ? 'rgba(248, 113, 113, 0.15)' : 'rgba(254, 226, 226, 0.9)',
    tableHeaderText: darkMode ? '#ffffff' : '#991b1b',
    tableRowAltBg: darkMode ? 'rgba(255,255,255,0.02)' : 'rgba(255,255,255,0.85)',
    tableRowHover: darkMode ? 'rgba(248,113,113,0.08)' : 'rgba(254,226,226,0.6)',
    infoSurface: darkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(254, 226, 226, 0.85)',
    infoBorder: darkMode ? 'rgba(239, 68, 68, 0.3)' : 'rgba(252, 165, 165, 0.65)',
    successTint: darkMode ? 'rgba(16, 185, 129, 0.2)' : 'rgba(187, 247, 208, 0.7)',
    neutralTint: darkMode ? 'rgba(156, 163, 175, 0.2)' : 'rgba(226,232,240,0.7)',
    paginationBg: darkMode
      ? 'linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(26,26,26,0.9) 100%)'
      : 'linear-gradient(135deg, rgba(255,255,255,0.96) 0%, rgba(254,242,242,0.96) 100%)',
    toggleGroupBg: darkMode ? 'rgba(255,255,255,0.08)' : 'rgba(148,163,184,0.12)',
    toggleActiveBg: darkMode ? 'rgba(255,255,255,0.14)' : '#ffffff',
    toggleActiveText: darkMode ? RedColorPalette.primaryLight : RedColorPalette.primary,
    toggleInactiveText: darkMode ? 'rgba(255,255,255,0.6)' : 'rgba(100,116,139,0.7)'
  }), [darkMode]);

  const excelButtonStyles = useMemo(() => ({
    base: darkMode
      ? 'linear-gradient(135deg, rgba(220,38,38,0.18), rgba(239,68,68,0.22))'
      : 'linear-gradient(135deg, #fee2e2, #fecaca)',
    hover: darkMode
      ? 'linear-gradient(135deg, rgba(220,38,38,0.28), rgba(239,68,68,0.32))'
      : 'linear-gradient(135deg, #fca5a5, #f87171)',
    text: darkMode ? '#fca5a5' : '#7f1d1d',
    border: darkMode ? 'rgba(248,113,113,0.55)' : '#f87171',
    shadow: darkMode ? '0 0.35rem 0.9rem rgba(239,68,68,0.25)' : '0 0.55rem 1.1rem rgba(248,113,113,0.28)'
  }), [darkMode]);

  const primaryActionButtonStyles = useMemo(() => ({
    base: `linear-gradient(135deg, ${RedColorPalette.primary}, ${RedColorPalette.primaryDark})`,
    hover: `linear-gradient(135deg, ${RedColorPalette.primaryLight}, ${RedColorPalette.primary})`,
    text: '#ffffff',
    shadow: '0 0.35rem 1rem rgba(239,68,68,0.35)'
  }), []);

  const statusStyles = useMemo<Record<Course['estado'], { background: string; color: string; border: string }>>(() => ({
    planificado: {
      background: darkMode ? 'rgba(248,113,113,0.18)' : 'rgba(254,215,215,0.95)',
      color: darkMode ? RedColorPalette.primaryLight : '#b91c1c',
      border: darkMode ? `1px solid ${RedColorPalette.primaryLight}` : '1px solid rgba(252,165,165,0.85)'
    },
    activo: {
      background: darkMode ? 'rgba(220,38,38,0.18)' : 'rgba(254, 226, 226, 0.95)',
      color: darkMode ? RedColorPalette.primary : '#b91c1c',
      border: darkMode ? `1px solid ${RedColorPalette.primary}` : '1px solid rgba(248,113,113,0.9)'
    },
    finalizado: {
      background: darkMode ? 'rgba(156,163,175,0.22)' : 'rgba(226,232,240,0.85)',
      color: darkMode ? '#9ca3af' : '#475569',
      border: darkMode ? '1px solid rgba(156,163,175,0.28)' : '1px solid rgba(203,213,225,0.8)'
    },
    cancelado: {
      background: darkMode ? 'rgba(239,68,68,0.2)' : 'rgba(254, 202, 202, 0.95)',
      color: darkMode ? RedColorPalette.primary : '#b91c1c',
      border: darkMode ? `1px solid ${RedColorPalette.primary}` : '1px solid rgba(252,165,165,0.9)'
    }
  }), [darkMode]);

  // Función para generar iniciales del tipo de curso
  const generateInitials = (nombre: string): string => {
    return nombre
      .split(' ')
      .map(word => word.charAt(0).toUpperCase())
      .join('')
      .substring(0, 2); // Máximo 2 caracteres
  };

  // Resolver el Tipo de Curso a partir de la lista cargada y los datos del curso
  const resolveTipoCursoForCurso = (curso: Course | null): TipoCursoOption | null => {
    if (!curso) return null;
    // 1) Por ID directo
    let tipo = tiposCursos.find(t => t.id_tipo_curso === curso.id_tipo_curso) || null;
    if (tipo) return tipo;
    // 2) Por nombre exacto (muchos cursos usan el nombre del tipo)
    tipo = tiposCursos.find(t => t.nombre.trim().toLowerCase() === curso.nombre.trim().toLowerCase()) || null;
    if (tipo) return tipo;
    // 3) Por iniciales: si el nombre del curso empieza por el nombre del tipo o viceversa
    const initials = generateInitials(curso.nombre);
    tipo = tiposCursos.find(t => generateInitials(t.nombre) === initials) || null;
    return tipo || null;
  };

  // Función para generar código automático validando contra BD
  const generateCourseCode = async (tipoId: number): Promise<string> => {
    const tipo = tiposCursos.find(t => t.id_tipo_curso === tipoId);
    if (!tipo) return '';

    const initials = generateInitials(tipo.nombre);

    try {
      // Consultar todos los códigos existentes en la BD
      const response = await fetch(`${API_BASE}/api/cursos?limit=1000`);
      if (!response.ok) {
        console.log('Error consultando cursos existentes, usando datos locales');
        // Fallback a datos locales si falla la consulta
        const existingCourses = cursos.filter(curso => {
          const tipoDelCurso = tiposCursos.find(t => t.id_tipo_curso === curso.id_tipo_curso);
          return tipoDelCurso && generateInitials(tipoDelCurso.nombre) === initials;
        });
        const nextNumber = existingCourses.length + 1;
        return `${initials}-${nextNumber.toString().padStart(3, '0')}`;
      }

      const cursosData = await response.json();
      const cursosReales = Array.isArray(cursosData) ? cursosData : (Array.isArray(cursosData?.rows) ? cursosData.rows : []);

      // Obtener todos los códigos existentes que empiecen con las mismas iniciales
      const existingCodes = cursosReales
        .map((curso: any) => curso.codigo_curso)
        .filter((codigo: string) => codigo && codigo.startsWith(`${initials}-`))
        .map((codigo: string) => {
          const numberPart = codigo.split('-')[1];
          return parseInt(numberPart) || 0;
        })
        .sort((a: number, b: number) => a - b);

      // Encontrar el siguiente número disponible
      let nextNumber = 1;
      for (const num of existingCodes) {
        if (num === nextNumber) {
          nextNumber++;
        } else {
          break;
        }
      }

      const newCode = `${initials}-${nextNumber.toString().padStart(3, '0')}`;

      console.log(`=== GENERACIÓN DE CÓDIGO (BD) ===`);
      console.log(`Tipo: ${tipo.nombre}`);
      console.log(`Iniciales: ${initials}`);
      console.log(`Códigos existentes en BD:`, existingCodes);
      console.log(`Próximo número: ${nextNumber}`);
      console.log(`Código generado: ${newCode}`);
      console.log(`================================`);

      return newCode;

    } catch (error) {
      console.error('Error generando código:', error);
      // Fallback a método simple
      const nextNumber = cursos.length + 1;
      return `${initials}-${nextNumber.toString().padStart(3, '0')}`;
    }
  };

  // Manejar cambio de tipo de curso
  const handleTipoCursoChange = async (e: React.ChangeEvent<HTMLSelectElement>) => {
    const tipoId = parseInt(e.target.value);
    setSelectedTipoCurso(tipoId);

    if (tipoId && (modalType === 'create' || modalType === 'edit')) {
      const tipo = tiposCursos.find(t => t.id_tipo_curso === tipoId);
      if (tipo) {
        // Generar código automático (ahora es async)
        try {
          const code = await generateCourseCode(tipoId);
          setAutoGeneratedCode(code);
        } catch (error) {
          console.error('Error generando código:', error);
          // Fallback simple
          const initials = generateInitials(tipo.nombre);
          const fallbackCode = `${initials}-001`;
          setAutoGeneratedCode(fallbackCode);
        }

        // Establecer nombre automático
        setAutoGeneratedName(tipo.nombre);
      }
    }
  };

  const fetchCursos = async (estadoFilter?: EstadoFilter) => {
    try {
      setLoading(true);
      setError(null);
      const estadoParam = (estadoFilter && estadoFilter !== 'todos') ? `estado=${estadoFilter}` : '';
      const qs = [estadoParam, 'limit=100'].filter(Boolean).join('&');
      const url = qs ? `${API_BASE}/api/cursos?${qs}` : `${API_BASE}/api/cursos`;
      const res = await fetch(url);
      if (!res.ok) throw new Error('No se pudo cargar cursos');
      const data = await res.json();
      const raw = Array.isArray(data) ? data : (Array.isArray((data as any)?.rows) ? (data as any).rows : (Array.isArray((data as any)?.data) ? (data as any).data : []));
      // map keys from list query to Course minimal view
      const normalized: Course[] = raw.map((row: any) => ({
        id_curso: row.id_curso,
        codigo_curso: row.codigo_curso,
        id_tipo_curso: row.id_tipo_curso ?? 0,
        nombre: row.nombre,
        horario: (row.horario || 'matutino') as 'matutino' | 'vespertino',
        capacidad_maxima: row.capacidad_maxima ?? 20,
        fecha_inicio: row.fecha_inicio?.slice(0, 10),
        fecha_fin: row.fecha_fin?.slice(0, 10),
        estado: row.estado,
        cupos_disponibles: row.cupos_disponibles ?? row.capacidad_maxima ?? 20
      }));
      setCursos(normalized);
    } catch (e: any) {
      setError(e.message || 'Error cargando cursos');
    } finally {
      setLoading(false);
    }
  };

  // Obtener un curso por ID con todos sus campos desde el backend
  const fetchCursoById = async (id: number): Promise<Course | null> => {
    try {
      const res = await fetch(`${API_BASE}/api/cursos/${id}`);
      if (!res.ok) return null;
      const row = await res.json();
      console.log('Curso recibido del backend:', row);
      console.log('Horario del curso:', row.horario);
      const c: Course = {
        id_curso: Number(row.id_curso ?? id),
        codigo_curso: String(row.codigo_curso ?? ''),
        id_tipo_curso: Number(row.id_tipo_curso ?? 0),
        nombre: String(row.nombre ?? ''),
        horario: (row.horario || 'matutino') as 'matutino' | 'vespertino',
        capacidad_maxima: Number(row.capacidad_maxima ?? 20),
        fecha_inicio: String((row.fecha_inicio ?? '').slice ? (row.fecha_inicio as string).slice(0, 10) : row.fecha_inicio ?? ''),
        fecha_fin: String((row.fecha_fin ?? '').slice ? (row.fecha_fin as string).slice(0, 10) : row.fecha_fin ?? ''),
        estado: (row.estado as Course['estado']) ?? 'activo',
        cupos_disponibles: Number(row.cupos_disponibles ?? row.capacidad_maxima ?? 20)
      };
      return c;
    } catch {
      return null;
    }
  };

  // Bloquear/Reanudar matrícula
  const handleToggleMatricula = async (curso: Course) => {
    // Determinar el nuevo estado basado en el estado actual
    let target: Course['estado'];
    if (curso.estado === 'cancelado') {
      // Si está cancelado (bloqueado), reanudar a activo o planificado según las fechas
      const hoy = new Date();
      const fechaInicio = new Date(curso.fecha_inicio);
      target = fechaInicio <= hoy ? 'activo' : 'planificado';
    } else {
      // Si no está cancelado, bloquear (cancelar temporalmente)
      target = 'cancelado';
    }

    try {
      setLoading(true);
      setError(null);
      const token = sessionStorage.getItem('auth_token');
      const res = await fetch(`${API_BASE}/api/cursos/${curso.id_curso}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ estado: target })
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || 'No se pudo actualizar el estado de matrícula');
      }

      // Actualizar estado local inmediatamente sin recargar
      setCursos(prev => prev.map(c =>
        c.id_curso === curso.id_curso
          ? { ...c, estado: target }
          : c
      ));

      // Mostrar mensaje de confirmación
      if (target === 'cancelado') {
        showToast.closed('Curso bloqueado. Las matrículas están suspendidas.', darkMode);
      } else {
        showToast.reopened('Curso reanudado. Las matrículas están habilitadas.', darkMode);
      }
    } catch (e: any) {
      setError(e.message || 'Error actualizando estado');
      showToast.error(`Error: ${e.message || 'No se pudo actualizar el estado del curso'}`, darkMode);
    } finally {
      setLoading(false);
    }
  };

  // Funcionalidad de clonado eliminada

  useEffect(() => {
    fetchCursos(filterEstado as EstadoFilter);
    // cargar catálogos
    (async () => {
      try {
        // Cargar TODOS los tipos de curso (activos e inactivos) para mostrar nombres correctos
        const resTipos = await fetch(`${API_BASE}/api/tipos-cursos?limit=100`);
        if (resTipos.ok) {
          const dataTipos = await resTipos.json();
          setTiposCursos(dataTipos);
          console.log('Tipos de curso cargados:', dataTipos.length);
        }
      } catch (e) {
        console.error('Error cargando tipos de curso:', e);
        // silencioso, no bloquear UI por catálogos
      }
    })();
  }, [filterEstado]);

  // Filtrado y paginación
  const filteredCursos = useMemo(() => {
    return cursos.filter(c => {
      const matchesSearch = c.nombre.toLowerCase().includes(searchTerm.toLowerCase()) ||
        c.codigo_curso.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesEstado = filterEstado === 'todos' || c.estado === filterEstado;
      return matchesSearch && matchesEstado;
    });
  }, [cursos, searchTerm, filterEstado]);

  const totalPages = Math.ceil(filteredCursos.length / itemsPerPage);
  const paginatedCursos = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return filteredCursos.slice(start, start + itemsPerPage);
  }, [filteredCursos, currentPage, itemsPerPage]);

  // Reset página al buscar o cambiar filtro
  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, filterEstado]);

  const handleCreateCurso = () => {
    setSelectedCurso(null);
    setModalType('create');
    setSelectedTipoCurso(null);
    setAutoGeneratedCode('');
    setAutoGeneratedName('');
    setShowModal(true);
  };

  const handleEditCurso = async (curso: Course) => {
    console.log('=== EDITAR CURSO (abrir) ===');
    console.log('Listado -> id_tipo_curso:', curso.id_tipo_curso);
    setModalType('edit');
    setLoading(true);
    // Intentar obtener el curso con todos sus campos (incluido id_tipo_curso real)
    const full = await fetchCursoById(curso.id_curso);
    let finalCurso = full ?? curso;
    // Si el backend no trae id_tipo_curso válido, intentar resolverlo
    if (!finalCurso.id_tipo_curso || finalCurso.id_tipo_curso === 0) {
      const resolved = resolveTipoCursoForCurso(finalCurso);
      if (resolved) {
        finalCurso = { ...finalCurso, id_tipo_curso: resolved.id_tipo_curso };
        console.log('id_tipo_curso resuelto por frontend:', resolved);
      }
    }
    console.log('Backend -> curso completo:', full);
    console.log('Usado para edición -> id_tipo_curso:', finalCurso.id_tipo_curso);

    setSelectedCurso(finalCurso);
    setSelectedTipoCurso(finalCurso.id_tipo_curso);
    setAutoGeneratedCode('');
    setAutoGeneratedName('');
    setShowModal(true);
    setLoading(false);
  };

  const handleViewCurso = async (curso: Course) => {
    // Cargar el curso completo desde el backend para tener todos los datos actualizados
    const cursoCompleto = await fetchCursoById(curso.id_curso);
    if (cursoCompleto) {
      setSelectedCurso(cursoCompleto);
      setModalType('view');
      setShowModal(true);
    } else {
      // Fallback: usar el curso de la lista si falla la carga
      setSelectedCurso(curso);
      setModalType('view');
      setShowModal(true);
    }
  };

  const handleFilterEstadoChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setFilterEstado(e.target.value as EstadoFilter);
  };

  // Quick-add handlers eliminados: ahora Tipos/Aulas se gestionan en módulos dedicados

  const confirmDeleteCurso = (curso: Course) => {
    setCursoToDelete(curso);
    setShowDeleteModal(true);
  };

  const closeDeleteModal = () => {
    setShowDeleteModal(false);
    setCursoToDelete(null);
  };

  const handleDeleteCurso = async () => {
    if (!cursoToDelete) return;
    try {
      setDeletingCurso(true);
      setError(null);
      const token = sessionStorage.getItem('auth_token');
      const res = await fetch(`${API_BASE}/api/cursos/${cursoToDelete.id_curso}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || 'No se pudo eliminar el curso');
      }
      const deletedName = cursoToDelete.nombre;
      setCursos(prev => prev.filter(c => c.id_curso !== cursoToDelete.id_curso));
      closeDeleteModal();
      showToast.deleted(`Curso "${deletedName}" eliminado correctamente`, darkMode);
    } catch (e: any) {
      setError(e.message || 'Error eliminando curso');
      showToast.error(e.message || 'Error eliminando curso', darkMode);
    } finally {
      setDeletingCurso(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    // Para crear curso, usar el código y nombre generados automáticamente
    const codigo = modalType === 'create' ? autoGeneratedCode : String(formData.get('codigo_curso') || '');
    const nombre = modalType === 'create' ?
      (String(formData.get('nombre') || '') || autoGeneratedName) :
      String(formData.get('nombre') || '');

    // Determinar estado automáticamente basado en fechas
    let estadoFinal = String(formData.get('estado') || 'activo') as Course['estado'];
    const fechaFin = new Date(String(formData.get('fecha_fin') || ''));
    const hoy = new Date();

    // Si es creación y la fecha de fin ya pasó, poner como finalizado
    if (modalType === 'create' && !isNaN(fechaFin.getTime()) && fechaFin < hoy) {
      estadoFinal = 'finalizado';
    }

    const courseData: Omit<Course, 'id_curso'> = {
      codigo_curso: codigo,
      id_tipo_curso: Number(formData.get('id_tipo_curso')),
      nombre: nombre,
      horario: String(formData.get('horario') || 'matutino') as 'matutino' | 'vespertino',
      capacidad_maxima: Number(formData.get('capacidad_maxima')),
      fecha_inicio: String(formData.get('fecha_inicio') || ''),
      fecha_fin: String(formData.get('fecha_fin') || ''),
      estado: estadoFinal
    };

    // Validar que se haya generado el código automáticamente
    if (modalType === 'create' && !courseData.codigo_curso) {
      setError('Debe seleccionar un tipo de curso para generar el código automáticamente');
      showToast.error('Debes seleccionar un tipo de curso para generar el código automáticamente', darkMode);
      return;
    }
    // Solo incluir codigo_curso cuando se edita; en creación el backend lo genera automáticamente
    const payload = (modalType === 'edit' && selectedCurso)
      ? { ...courseData, codigo_curso: String(formData.get('codigo_curso') || '').trim() }
      : courseData;
    // Validación simple en frontend
    // Código es obligatorio solo en edición (en creación se genera automáticamente)
    if (modalType === 'edit' && !('codigo_curso' in payload)) {
      setError('El código del curso es obligatorio');
      showToast.error('El código del curso es obligatorio', darkMode);
      return;
    }
    if (!payload.id_tipo_curso) {
      setError('Debes seleccionar un tipo de curso');
      showToast.error('Debes seleccionar un tipo de curso', darkMode);
      return;
    }

    // Validar que la duración del curso coincida con el tipo de curso seleccionado
    const tipoSeleccionado = tiposCursos.find(t => t.id_tipo_curso === payload.id_tipo_curso);
    if (tipoSeleccionado && tipoSeleccionado.duracion_meses != null) {
      const fechaInicio = new Date(payload.fecha_inicio);
      const fechaFin = new Date(payload.fecha_fin);

      if (!isNaN(fechaInicio.getTime()) && !isNaN(fechaFin.getTime())) {
        // Calcular la diferencia en meses
        const diffYears = fechaFin.getFullYear() - fechaInicio.getFullYear();
        const diffMonths = fechaFin.getMonth() - fechaInicio.getMonth();
        const totalMonths = diffYears * 12 + diffMonths;

        // Validar que la diferencia sea igual a la duración del tipo de curso (con un margen de 1 mes)
        if (Math.abs(totalMonths - tipoSeleccionado.duracion_meses) > 1) {
          // Mostrar alerta visual profesional
          showToast.error(
            `La duración del curso debe ser de ${tipoSeleccionado.duracion_meses} meses según el tipo de curso seleccionado. La duración actual es de ${totalMonths} meses.`,
            darkMode
          );
          return;
        }
      }
    }

    // Validación adicional: verificar que el código no esté duplicado en BD
    if (modalType === 'create' && payload.codigo_curso) {
      try {
        const response = await fetch(`${API_BASE}/api/cursos?limit=1000`);
        if (response.ok) {
          const cursosData = await response.json();
          const cursosReales = Array.isArray(cursosData) ? cursosData : (Array.isArray(cursosData?.rows) ? cursosData.rows : []);

          const codigoExistente = cursosReales.find((curso: any) =>
            curso.codigo_curso && curso.codigo_curso.toLowerCase() === payload.codigo_curso.toLowerCase()
          );

          if (codigoExistente) {
            setError(`El código "${payload.codigo_curso}" ya existe en la base de datos. Regenerando...`);
            showToast.warning(`El código "${payload.codigo_curso}" ya existe. Generando uno nuevo.`, darkMode);
            // Regenerar código automáticamente
            try {
              const nuevoCodigo = await generateCourseCode(payload.id_tipo_curso);
              setAutoGeneratedCode(nuevoCodigo);
              return;
            } catch (genError) {
              setError('Error regenerando código. Intenta de nuevo.');
              showToast.error('Error regenerando el código del curso. Intenta nuevamente.', darkMode);
              return;
            }
          }
        }
      } catch (validateError) {
        console.log('Error validando código duplicado:', validateError);
        // Continuar con la creación si falla la validación
      }
    }
    const dInicio = new Date(payload.fecha_inicio);
    const dFin = new Date(payload.fecha_fin);
    if (!(dInicio instanceof Date) || isNaN(dInicio.getTime())) {
      setError('Fecha de inicio inválida');
      showToast.error('La fecha de inicio es inválida', darkMode);
      return;
    }
    if (!(dFin instanceof Date) || isNaN(dFin.getTime())) {
      setError('Fecha de fin inválida');
      showToast.error('La fecha de fin es inválida', darkMode);
      return;
    }
    if (dFin <= dInicio) {
      setError('La fecha de fin debe ser mayor a la fecha de inicio');
      showToast.error('La fecha de fin debe ser mayor a la fecha de inicio', darkMode);
      return;
    }

    try {
      setLoading(true);
      setError(null);
      if (modalType === 'create') {
        const token = sessionStorage.getItem('auth_token');
        console.log('Token obtenido:', token ? 'Existe' : 'NO EXISTE');
        console.log('Payload a enviar:', payload);

        const res = await fetch(`${API_BASE}/api/cursos`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify(payload)
        });

        console.log(' Status de respuesta:', res.status);

        if (!res.ok) {
          let msg = 'No se pudo crear el curso';
          try {
            const j = await res.json();
            console.log('-Error del servidor:', j);
            if (j?.error) msg = j.error;
          } catch { }
          throw new Error(msg);
        }
        const newCurso = await res.json();
        // Agregar el nuevo curso a la lista inmediatamente
        setCursos(prev => [newCurso, ...prev]);
        showToast.success('Curso creado correctamente', darkMode);
      } else if (modalType === 'edit' && selectedCurso) {
        const token = sessionStorage.getItem('auth_token');
        const res = await fetch(`${API_BASE}/api/cursos/${selectedCurso.id_curso}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify(payload)
        });
        if (!res.ok) {
          let msg = 'No se pudo actualizar el curso';
          try { const j = await res.json(); if (j?.error) msg = j.error; } catch { }
          throw new Error(msg);
        }
        const updatedCurso = await res.json();
        // Actualizar el curso en la lista inmediatamente
        setCursos(prev => prev.map(c =>
          c.id_curso === selectedCurso.id_curso
            ? { ...c, ...updatedCurso }
            : c
        ));
        showToast.success('Curso actualizado correctamente', darkMode);
      }
      setShowModal(false);
    } catch (e: any) {
      setError(e.message || 'Error guardando curso');
      showToast.error(e.message || 'Error guardando curso', darkMode);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      {/* Header */}
      <AdminSectionHeader
        title="Gestión de Cursos"
        subtitle="Administra los cursos disponibles en la escuela"
        marginBottom={isMobile ? '12px' : '1.125rem'}
      />

      {/* Advertencia si no hay tipos de curso */}
      {tiposCursos.length === 0 && (
        <GlassEffect variant="card" tint="warning" intensity="light" style={{ marginBottom: '1rem' }}>
          <div style={{
            color: mapToRedScheme('#fbbf24')
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '0.75rem' }}>
              <span style={{ fontWeight: 600 }}>Primero crea un "Tipo de Curso" en el módulo Tipos de Curso para poder crear cursos.</span>
            </div>
          </div>
        </GlassEffect>
      )}

      {/* Controles */}
      <GlassEffect variant="card" tint="neutral" intensity="light" style={{ marginBottom: isMobile ? '12px' : '1rem' }}>
        <div className="responsive-filters">
          <div style={{ display: 'flex', flexDirection: isSmallScreen ? 'column' : 'row', gap: '0.75rem', alignItems: isSmallScreen ? 'stretch' : 'center', flex: 1, width: isSmallScreen ? '100%' : 'auto' }}>
            {/* Búsqueda */}
            <div style={{ position: 'relative', minWidth: isSmallScreen ? 'auto' : '17.5rem', width: isSmallScreen ? '100%' : 'auto' }}>
              <Search size={16} style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: themeColors.iconMuted }} />
              <input
                type="text"
                placeholder="Buscar cursos o instructores..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.625em 0.625em 0.625em 2.375em',
                  background: darkMode ? 'rgba(255,255,255,0.1)' : themeColors.controlBg,
                  border: `0.0625rem solid ${themeColors.controlBorder}`,
                  borderRadius: '0.625em',
                  color: themeColors.textPrimary,
                  fontSize: '0.8rem',
                  boxShadow: darkMode ? 'none' : '0 1px 2px rgba(15,23,42,0.08)'
                }}
              />
            </div>

            {/* Filtros */}
            <div style={{ minWidth: isSmallScreen ? 'auto' : 'min(12.5rem, 25vw)', width: isSmallScreen ? '100%' : 'auto' }}>
              <StyledSelect
                name="filterEstado"
                value={filterEstado}
                onChange={handleFilterEstadoChange}
                darkMode={darkMode}
                options={[
                  { value: 'todos', label: 'Todos los estados' },
                  { value: 'planificado', label: 'Planificados' },
                  { value: 'activo', label: 'Activos' },
                  { value: 'finalizado', label: 'Finalizados' },
                  { value: 'cancelado', label: 'Cancelados' },
                ]}
              />
            </div>

            {/* Toggle Vista y Botón Excel */}
            <div style={{ display: 'flex', gap: '0.375rem', alignItems: 'center' }}>
              <div style={{
                display: 'flex',
                gap: '0.375rem',
                background: themeColors.toggleGroupBg,
                borderRadius: '0.65rem',
                padding: '0.1875rem',
                border: 'none',
                boxShadow: 'none'
              }}>
                <button
                  onClick={() => setViewMode('cards')}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '0.3em',
                    padding: isMobile ? '0.45em 0.8em' : '0.45em 0.95em',
                    background: viewMode === 'cards' ? themeColors.toggleActiveBg : 'transparent',
                    border: 'none',
                    borderRadius: '0.5em',
                    color: viewMode === 'cards' ? themeColors.toggleActiveText : themeColors.toggleInactiveText,
                    cursor: 'pointer',
                    fontSize: '0.8rem',
                    fontWeight: 600,
                    transition: 'all 0.2s ease',
                    flex: isSmallScreen ? 1 : 'initial'
                  }}
                >
                  <Grid size={16} color={viewMode === 'cards' ? themeColors.toggleActiveText : themeColors.toggleInactiveText} /> {!isMobile && 'Tarjetas'}
                </button>
                <button
                  onClick={() => setViewMode('table')}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '0.3em',
                    padding: isMobile ? '0.45em 0.8em' : '0.5em 1em',
                    background: viewMode === 'table' ? themeColors.toggleActiveBg : 'transparent',
                    border: 'none',
                    borderRadius: '0.5em',
                    color: viewMode === 'table' ? themeColors.toggleActiveText : themeColors.toggleInactiveText,
                    cursor: 'pointer',
                    fontSize: '0.8rem',
                    fontWeight: 600,
                    transition: 'all 0.2s ease',
                    flex: isSmallScreen ? 1 : 'initial'
                  }}
                >
                  <List size={16} color={viewMode === 'table' ? themeColors.toggleActiveText : themeColors.toggleInactiveText} /> {!isMobile && 'Tabla'}
                </button>
              </div>

              {/* Botón Excel */}
              <button
                onClick={async () => {
                  try {
                    const response = await fetch(`${API_BASE}/api/cursos/reporte/excel`);
                    if (!response.ok) throw new Error('Error descargando reporte');
                    const blob = await response.blob();
                    const url = window.URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `Reporte_Cursos_${new Date().toISOString().split('T')[0]}.xlsx`;
                    document.body.appendChild(a);
                    a.click();
                    window.URL.revokeObjectURL(url);
                    document.body.removeChild(a);
                    showToast.success('Reporte descargado exitosamente', darkMode);
                  } catch (error) {
                    console.error('Error:', error);
                    showToast.error('Error al descargar el reporte', darkMode);
                  }
                }}
                style={{
                  padding: isMobile ? '0.625em 1em' : '0.75em 1.25em',
                  fontSize: '0.8rem',
                  borderRadius: '0.625rem',
                  border: 'none',
                  background: primaryActionButtonStyles.base,
                  color: primaryActionButtonStyles.text,
                  cursor: 'pointer',
                  width: isSmallScreen ? '100%' : 'auto',
                  fontWeight: '600',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '0.375rem',
                  transition: 'all 0.2s ease',
                  boxShadow: primaryActionButtonStyles.shadow
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = primaryActionButtonStyles.hover;
                  e.currentTarget.style.transform = 'translateY(-1px)';
                  e.currentTarget.style.boxShadow = '0 0.5rem 1.25rem rgba(239,68,68,0.4)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = primaryActionButtonStyles.base;
                  e.currentTarget.style.transform = 'translateY(0)';
                  e.currentTarget.style.boxShadow = primaryActionButtonStyles.shadow;
                }}
              >
                <Sheet size={16} color={primaryActionButtonStyles.text} /> Descargar Excel
              </button>
            </div>
          </div>

          {/* Botón Crear */}
          <button
            onClick={handleCreateCurso}
            disabled={tiposCursos.length === 0}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5em',
              padding: isMobile ? '0.625em 1em' : '0.75em 1.5em',
              background: tiposCursos.length === 0 ? 'rgba(239, 68, 68, 0.3)' : primaryActionButtonStyles.base,
              border: 'none',
              borderRadius: '0.625em',
              color: primaryActionButtonStyles.text,
              fontSize: '0.8rem',
              fontWeight: '600',
              cursor: tiposCursos.length === 0 ? 'not-allowed' : 'pointer',
              boxShadow: tiposCursos.length === 0 ? 'none' : primaryActionButtonStyles.shadow,
              width: isSmallScreen ? '100%' : 'auto'
            }}
          >
            <Plus size={16} color="currentColor" />
            Nuevo Curso
          </button>
        </div>

        {/* Info de resultados */}
        <div style={{ color: themeColors.textSecondary, fontSize: '0.75rem', marginTop: '0.75rem' }}>
          {searchTerm || filterEstado !== 'todos'
            ? `${filteredCursos.length} de ${cursos.length} cursos`
            : `Total: ${cursos.length} cursos`}
        </div>
      </GlassEffect>

      {/* Vista Cards */}
      {viewMode === 'cards' && paginatedCursos.length > 0 && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: isMobile ? '1fr' : 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: isMobile ? '12px' : '1rem',
          marginBottom: isMobile ? '12px' : '1.125rem'
        }}>
          {paginatedCursos.map((curso) => {
            const estadoConfig = {
              planificado: { ...statusStyles.planificado, icon: PlayCircle },
              activo: { ...statusStyles.activo, icon: CheckCircle2 },
              finalizado: { ...statusStyles.finalizado, icon: Lock },
              cancelado: { ...statusStyles.cancelado, icon: Ban }
            }[curso.estado] || { ...statusStyles.planificado, icon: AlertCircle };

            const EstadoIcon = estadoConfig.icon;
            const viewActionColor = darkMode ? RedColorPalette.primary : '#b91c1c';
            const editActionColor = themeColors.textPrimary;
            const deleteActionColor = excelButtonStyles.text;
            const toggleActionColor = curso.estado === 'cancelado'
              ? (darkMode ? mapToRedScheme('#10b981') : '#047857')
              : (darkMode ? RedColorPalette.primary : '#b91c1c');

            return (
              <GlassEffect
                key={curso.id_curso}
                variant="card"
                tint="neutral"
                intensity="light"
                hover
                animated
              >
                <div style={{ marginBottom: '0.75rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '0.375rem' }}>
                    <span style={{
                      color: themeColors.textMuted,
                      fontSize: '0.7rem',
                      background: darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(248,250,252,0.9)',
                      padding: '3px 0.375rem',
                      borderRadius: '0.3125rem'
                    }}>
                      {curso.codigo_curso}
                    </span>
                    <span
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.1875rem',
                        padding: '3px 0.5rem',
                        borderRadius: 6,
                        background: estadoConfig.background,
                        border: estadoConfig.border,
                        color: estadoConfig.color,
                        fontWeight: 700,
                        fontSize: '0.65rem',
                        textTransform: 'uppercase',
                      }}
                    >
                      <EstadoIcon size={10} color={estadoConfig.color} />
                      {curso.estado}
                    </span>
                  </div>
                  <h3 style={{
                    color: themeColors.textPrimary,
                    margin: '0 0 0.5rem 0'
                  }}>
                    {curso.nombre}
                  </h3>
                </div>

                <div style={{
                  display: 'grid',
                  gridTemplateColumns: '1fr 1fr',
                  gap: '0.625rem',
                  marginBottom: '0.75rem',
                  paddingTop: '0.625rem',
                  borderTop: `1px solid ${themeColors.controlBorder}`
                }}>
                  <div>
                    <div style={{ color: themeColors.textMuted, fontSize: '0.65rem', marginBottom: '0.1875rem' }}>
                      Fecha Inicio
                    </div>
                    <div style={{ color: themeColors.textPrimary, fontSize: '0.75rem', fontWeight: 600 }}>
                      {curso.fecha_inicio}
                    </div>
                  </div>
                  <div>
                    <div style={{ color: themeColors.textMuted, fontSize: '0.65rem', marginBottom: '0.1875rem' }}>
                      Fecha Fin
                    </div>
                    <div style={{ color: themeColors.textPrimary, fontSize: '0.75rem', fontWeight: 600 }}>
                      {curso.fecha_fin}
                    </div>
                  </div>
                  <div>
                    <div style={{ color: themeColors.textMuted, fontSize: '0.65rem', marginBottom: '0.1875rem' }}>
                      Cupos
                    </div>
                    <div style={{ color: curso.estado === 'cancelado' ? statusStyles.cancelado.color : mapToRedScheme('#10b981'), fontSize: '0.75rem', fontWeight: 700 }}>
                      {curso.estado === 'cancelado' ? 'N/A' : `${curso.cupos_disponibles || 0} / ${curso.capacidad_maxima}`}
                    </div>
                  </div>
                  <div>
                    <div style={{ color: themeColors.textMuted, fontSize: '0.65rem', marginBottom: '0.1875rem' }}>
                      Horario
                    </div>
                    <div style={{ color: themeColors.textPrimary, fontSize: '0.75rem', fontWeight: 600, textTransform: 'capitalize' }}>
                      {curso.horario}
                    </div>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '0.375rem', flexWrap: 'wrap' }}>
                  <button
                    onClick={() => handleViewCurso(curso)}
                    style={{
                      flex: '1 1 auto',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '0.3125rem',
                      padding: '0.5rem',
                      background: darkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(254, 226, 226, 0.75)',
                      border: darkMode ? `1px solid ${RedColorPalette.primary}` : '1px solid rgba(252, 165, 165, 0.85)',
                      borderRadius: '0.5rem',
                      color: viewActionColor,
                      fontSize: '0.7rem',
                      fontWeight: 600,
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(254, 202, 202, 0.92)';
                      e.currentTarget.style.transform = 'scale(1.05) translateY(-1px)';
                      e.currentTarget.style.boxShadow = `0 0.25rem 0.75rem ${RedColorPalette.primary}40`;
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(254, 226, 226, 0.75)';
                      e.currentTarget.style.transform = 'scale(1) translateY(0)';
                      e.currentTarget.style.boxShadow = 'none';
                    }}
                  >
                    <Eye size={12} color={viewActionColor} /> Ver
                  </button>
                  <button
                    onClick={() => handleEditCurso(curso)}
                    style={{
                      flex: '1 1 auto',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '0.375rem',
                      padding: '0.625rem',
                      background: darkMode ? 'rgba(255,255,255,0.08)' : '#ffffff',
                      border: `1px solid ${themeColors.controlBorder}`,
                      borderRadius: '0.625rem',
                      color: editActionColor,
                      fontSize: '0.8rem',
                      fontWeight: 600,
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(255,255,255,0.15)' : 'rgba(248,250,252,0.95)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(255,255,255,0.08)' : '#ffffff';
                    }}
                  >
                    <Edit size={14} color={editActionColor} /> Editar
                  </button>
                  <button
                    onClick={() => confirmDeleteCurso(curso)}
                    style={{
                      padding: '10px 0.75rem',
                      background: darkMode ? 'rgba(239, 68, 68, 0.15)' : 'rgba(254, 226, 226, 0.85)',
                      border: `1px solid ${excelButtonStyles.border}`,
                      borderRadius: '0.625rem',
                      color: deleteActionColor,
                      fontSize: '0.85rem',
                      fontWeight: 600,
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.25)' : 'rgba(254, 202, 202, 0.95)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.15)' : 'rgba(254, 226, 226, 0.85)';
                    }}
                  >
                    <Trash2 size={14} color={deleteActionColor} />
                  </button>
                  <button
                    onClick={() => handleToggleMatricula(curso)}
                    title={curso.estado === 'cancelado' ? 'Reanudar matrículas' : 'Cerrar matrículas'}
                    style={{
                      flex: '1 1 100%',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '0.375rem',
                      padding: '0.625rem',
                      background: curso.estado === 'cancelado'
                        ? (darkMode ? 'rgba(16, 185, 129, 0.15)' : 'rgba(187, 247, 208, 0.8)')
                        : (darkMode ? 'rgba(239, 68, 68, 0.15)' : 'rgba(254, 226, 226, 0.85)'),
                      border: curso.estado === 'cancelado'
                        ? `1px solid ${darkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(134, 239, 172, 0.9)'}`
                        : `1px solid ${excelButtonStyles.border}`,
                      borderRadius: '0.625rem',
                      color: toggleActionColor,
                      fontSize: '0.85rem',
                      fontWeight: 600,
                      cursor: 'pointer',
                      transition: 'all 0.2s ease',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.background = curso.estado === 'cancelado'
                        ? (darkMode ? 'rgba(16, 185, 129, 0.25)' : 'rgba(187, 247, 208, 0.95)')
                        : (darkMode ? 'rgba(239, 68, 68, 0.25)' : 'rgba(254, 202, 202, 0.95)');
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.background = curso.estado === 'cancelado'
                        ? (darkMode ? 'rgba(16, 185, 129, 0.15)' : 'rgba(187, 247, 208, 0.8)')
                        : (darkMode ? 'rgba(239, 68, 68, 0.15)' : 'rgba(254, 226, 226, 0.85)');
                    }}
                  >
                    {curso.estado === 'cancelado'
                      ? <Unlock size={14} color={toggleActionColor} />
                      : <Lock size={14} color={toggleActionColor} />}
                    {curso.estado === 'cancelado' ? 'Reanudar' : 'Cerrar'}
                  </button>
                </div>
              </GlassEffect>
            );
          })}
        </div>
      )}

      {/* Vista Tabla */}
      {viewMode === 'table' && paginatedCursos.length > 0 && (
        <>
          {/* Indicador de scroll en móvil */}
          {isSmallScreen && (
            <div style={{
              background: 'rgba(239, 68, 68, 0.1)',
              border: '1px solid rgba(239, 68, 68, 0.3)',
              borderRadius: '0.5rem',
              padding: '8px 0.75rem',
              marginBottom: '0.75rem',
              color: '#ef4444',
              fontSize: '0.75rem',
              textAlign: 'center',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.375rem'
            }}>
              <span>👉</span>
              <span>Desliza horizontalmente para ver toda la tabla</span>
              <span>👈</span>
            </div>
          )}

          <div
            className="responsive-table-container"
            style={{
              background: themeColors.sectionSurface,
              border: `1px solid ${themeColors.sectionBorder}`,
              borderRadius: isMobile ? '0.75rem' : '1rem',
              overflow: 'auto',
              marginBottom: isMobile ? '0.75rem' : '1.5rem',
              WebkitOverflowScrolling: 'touch'
            }}
          >
            <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: isSmallScreen ? 'min(56.25rem, 95vw)' : 'auto' }}>
              <thead>
                <tr style={{
                  background: themeColors.tableHeaderBg,
                  borderBottom: `1px solid ${darkMode ? 'rgba(248, 113, 113, 0.3)' : 'rgba(252, 165, 165, 0.8)'}`
                }}>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'left',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '12%'
                  }}>
                    Código
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'left',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '20%'
                  }}>
                    NOMBRE
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'center',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '12%'
                  }}>
                    Fecha Inicio
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'center',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '12%'
                  }}>
                    Fecha Fin
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'center',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '12%'
                  }}>
                    Cupos
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'center',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '12%'
                  }}>
                    Estado
                  </th>
                  <th style={{
                    padding: '10px 0.75rem',
                    color: themeColors.tableHeaderText,
                    textAlign: 'center',
                    fontWeight: 600,
                    fontSize: '0.75rem',
                    textTransform: 'uppercase',
                    width: '20%'
                  }}>
                    Acciones
                  </th>
                </tr>
              </thead>
              <tbody>
                {paginatedCursos.map((curso, index) => {
                  const estadoBadge = statusStyles[curso.estado];
                  const viewActionColor = darkMode ? RedColorPalette.primary : '#b91c1c';
                  const editActionColor = themeColors.textPrimary;
                  const deleteActionColor = excelButtonStyles.text;
                  const toggleActionColor = curso.estado === 'cancelado'
                    ? (darkMode ? mapToRedScheme('#10b981') : '#047857')
                    : (darkMode ? '#9ca3af' : '#475569');
                  const toggleIconColor = curso.estado === 'cancelado'
                    ? (darkMode ? mapToRedScheme('#10b981') : '#047857')
                    : (darkMode ? '#9ca3af' : '#475569');
                  return (
                    <tr
                      key={curso.id_curso}
                      style={{
                        borderBottom: `1px solid ${darkMode ? 'rgba(255,255,255,0.08)' : 'rgba(226,232,240,0.7)'}`,
                        background: index % 2 === 0 ? themeColors.tableRowAltBg : 'transparent',
                        transition: 'all 0.2s ease',
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = themeColors.tableRowHover;
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = index % 2 === 0 ? themeColors.tableRowAltBg : 'transparent';
                      }}
                    >
                      <td style={{
                        padding: '0.75rem',
                        color: themeColors.textPrimary,
                        fontWeight: 600,
                        fontSize: '0.8rem'
                      }}>
                        {curso.codigo_curso}
                      </td>
                      <td className="table-nombre-uppercase" style={{
                        padding: '0.75rem',
                        color: themeColors.textPrimary,
                        fontWeight: 600,
                        fontSize: '0.8rem'
                      }}>
                        {curso.nombre}
                      </td>
                      <td style={{
                        padding: '0.75rem',
                        color: themeColors.textSecondary,
                        textAlign: 'center',
                        fontSize: '0.75rem'
                      }}>
                        {curso.fecha_inicio}
                      </td>
                      <td style={{
                        padding: '0.75rem',
                        color: themeColors.textSecondary,
                        textAlign: 'center',
                        fontSize: '0.75rem'
                      }}>
                        {curso.fecha_fin}
                      </td>
                      <td style={{ padding: '0.75rem', textAlign: 'center' }}>
                        {curso.estado === 'cancelado' ? (
                          <span style={{
                            display: 'inline-block',
                            padding: '4px 0.625rem',
                            borderRadius: '0.5rem',
                            fontSize: '0.7rem',
                            fontWeight: 700,
                            background: themeColors.neutralTint,
                            color: darkMode ? '#9ca3af' : '#475569',
                            textTransform: 'uppercase',
                            border: `1px solid ${darkMode ? 'rgba(156, 163, 175, 0.3)' : 'rgba(203,213,225,0.9)'}`
                          }}>
                            Cerrado
                          </span>
                        ) : (
                          <span style={{
                            display: 'inline-block',
                            padding: '4px 0.625rem',
                            borderRadius: '0.5rem',
                            fontSize: '0.7rem',
                            fontWeight: 700,
                            background: (curso.cupos_disponibles || 0) > 0
                              ? (darkMode ? 'rgba(16, 185, 129, 0.2)' : 'rgba(187, 247, 208, 0.85)')
                              : (darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(254, 226, 226, 0.85)'),
                            color: (curso.cupos_disponibles || 0) > 0
                              ? (darkMode ? mapToRedScheme('#10b981') : '#047857')
                              : (darkMode ? RedColorPalette.primary : '#b91c1c'),
                            border: (curso.cupos_disponibles || 0) > 0
                              ? `1px solid ${darkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(74, 222, 128, 0.8)'}`
                              : `1px solid ${darkMode ? 'rgba(239, 68, 68, 0.3)' : 'rgba(252, 165, 165, 0.8)'}`
                          }}>
                            {curso.cupos_disponibles || curso.capacidad_maxima || 0} / {curso.capacidad_maxima || 0}
                          </span>
                        )}
                      </td>
                      <td style={{ padding: '0.75rem', textAlign: 'center' }}>
                        <span style={{
                          display: 'inline-block',
                          padding: '4px 0.625rem',
                          borderRadius: '0.5rem',
                          fontSize: '0.7rem',
                          fontWeight: 700,
                          textTransform: 'uppercase',
                          background: estadoBadge.background,
                          border: estadoBadge.border,
                          color: estadoBadge.color
                        }}>
                          {curso.estado}
                        </span>
                      </td>
                      <td style={{ padding: '0.75rem' }}>
                        <div style={{ display: 'flex', gap: '0.375rem', justifyContent: 'center' }}>
                          <button
                            onClick={() => handleViewCurso(curso)}
                            style={{
                              background: darkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(254, 226, 226, 0.75)',
                              border: darkMode ? `1px solid ${RedColorPalette.primary}` : '1px solid rgba(252, 165, 165, 0.85)',
                              color: viewActionColor,
                              padding: '6px 0.625rem',
                              borderRadius: '0.375rem',
                              cursor: 'pointer',
                              fontSize: '0.75rem',
                              fontWeight: '600',
                              display: 'flex',
                              alignItems: 'center',
                              gap: '0.25rem',
                              transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                              transform: 'translateZ(0)'
                            }}
                            onMouseEnter={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(254, 202, 202, 0.92)';
                              e.currentTarget.style.transform = 'scale(1.05) translateY(-1px)';
                              e.currentTarget.style.boxShadow = `0 0.25rem 0.75rem ${RedColorPalette.primary}40`;
                            }}
                            onMouseLeave={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(254, 226, 226, 0.75)';
                              e.currentTarget.style.transform = 'scale(1) translateY(0)';
                              e.currentTarget.style.boxShadow = 'none';
                            }}
                          >
                            <Eye size={12} color={viewActionColor} />
                            Ver
                          </button>
                          <button
                            onClick={() => handleEditCurso(curso)}
                            style={{
                              background: darkMode ? 'rgba(239, 68, 68, 0.1)' : '#ffffff',
                              border: `1px solid ${themeColors.controlBorder}`,
                              color: editActionColor,
                              padding: '6px 0.625rem',
                              borderRadius: '0.375rem',
                              cursor: 'pointer',
                              fontSize: '0.75rem',
                              fontWeight: '600',
                              display: 'flex',
                              alignItems: 'center',
                              gap: '0.25rem',
                              transition: 'all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                              transform: 'translateZ(0)'
                            }}
                            onMouseEnter={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(248,250,252,0.95)';
                              e.currentTarget.style.transform = 'scale(1.05) translateY(-1px)';
                              e.currentTarget.style.boxShadow = `0 0.25rem 0.75rem ${RedColorPalette.primary}40`;
                            }}
                            onMouseLeave={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.1)' : '#ffffff';
                              e.currentTarget.style.transform = 'scale(1) translateY(0)';
                              e.currentTarget.style.boxShadow = 'none';
                            }}
                          >
                            <Edit size={12} color={editActionColor} />
                            Editar
                          </button>
                          <button
                            onClick={() => confirmDeleteCurso(curso)}
                            style={{
                              background: darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(254, 226, 226, 0.85)',
                              border: `1px solid ${excelButtonStyles.border}`,
                              color: deleteActionColor,
                              padding: '6px 0.625rem',
                              borderRadius: '0.375rem',
                              cursor: 'pointer',
                              fontSize: '0.75rem',
                              fontWeight: '600',
                              display: 'flex',
                              alignItems: 'center',
                              gap: '0.25rem',
                              transition: 'all 0.2s ease'
                            }}
                            onMouseEnter={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.3)' : 'rgba(254, 202, 202, 0.95)';
                            }}
                            onMouseLeave={(e) => {
                              e.currentTarget.style.background = darkMode ? 'rgba(239, 68, 68, 0.2)' : 'rgba(254, 226, 226, 0.85)';
                            }}
                          >
                            <Trash2 size={12} color={deleteActionColor} />
                          </button>
                          <button
                            onClick={() => handleToggleMatricula(curso)}
                            title={curso.estado === 'cancelado' ? 'Reanudar matrículas' : 'Cerrar matrículas'}
                            style={{
                              background: curso.estado === 'cancelado'
                                ? (darkMode ? 'rgba(16, 185, 129, 0.2)' : 'rgba(187, 247, 208, 0.8)')
                                : (darkMode ? 'rgba(156, 163, 175, 0.2)' : 'rgba(226,232,240,0.75)'),
                              border: curso.estado === 'cancelado'
                                ? `1px solid ${darkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(134, 239, 172, 0.85)'}`
                                : `1px solid ${darkMode ? 'rgba(156, 163, 175, 0.3)' : 'rgba(203,213,225,0.85)'}`,
                              color: toggleActionColor,
                              padding: '6px 0.625rem',
                              borderRadius: '0.375rem',
                              fontSize: '0.75rem',
                              fontWeight: '600',
                              display: 'flex',
                              alignItems: 'center',
                              gap: '0.25rem',
                              cursor: 'pointer',
                              transition: 'all 0.2s ease',
                              whiteSpace: 'nowrap'
                            }}
                            onMouseEnter={(e) => {
                              e.currentTarget.style.background = curso.estado === 'cancelado'
                                ? (darkMode ? 'rgba(16, 185, 129, 0.3)' : 'rgba(187, 247, 208, 0.95)')
                                : (darkMode ? 'rgba(156, 163, 175, 0.3)' : 'rgba(226,232,240,0.95)');
                            }}
                            onMouseLeave={(e) => {
                              e.currentTarget.style.background = curso.estado === 'cancelado'
                                ? (darkMode ? 'rgba(16, 185, 129, 0.2)' : 'rgba(187, 247, 208, 0.8)')
                                : (darkMode ? 'rgba(156, 163, 175, 0.2)' : 'rgba(226,232,240,0.75)');
                            }}
                          >
                            {curso.estado === 'cancelado'
                              ? <Unlock size={12} color={toggleIconColor} />
                              : <Lock size={12} color={toggleIconColor} />}
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      )}

      {/* Estados vacíos y errores */}
      {loading && (
        <div style={{
          color: themeColors.textSecondary,
          padding: '60px 1.25rem',
          textAlign: 'center',
          fontSize: '1rem',
          background: themeColors.sectionSurface,
          border: `1px solid ${themeColors.sectionBorder}`,
          borderRadius: '1rem',
          marginBottom: '1.5rem'
        }}>
          Cargando cursos...
        </div>
      )}
      {error && (
        <div style={{
          color: excelButtonStyles.text,
          padding: '1.25rem',
          textAlign: 'center',
          background: themeColors.infoSurface,
          border: `1px solid ${themeColors.infoBorder}`,
          borderRadius: '1rem',
          fontSize: '0.95rem',
          marginBottom: '1.5rem'
        }}>
          {error}
        </div>
      )}
      {!loading && !error && filteredCursos.length === 0 && (
        <div style={{
          color: themeColors.textSecondary,
          padding: '60px 1.25rem',
          textAlign: 'center',
          fontSize: '1rem',
          background: themeColors.sectionSurface,
          border: `1px solid ${themeColors.sectionBorder}`,
          borderRadius: '1rem',
          marginBottom: '1.5rem'
        }}>
          {searchTerm || filterEstado !== 'todos' ? 'No se encontraron cursos' : 'No hay cursos registrados'}
        </div>
      )}

      {/* Paginación */}
      {!loading && filteredCursos.length > 0 && (
        <div className="pagination-container" style={{
          display: 'flex',
          flexDirection: isMobile ? 'column' : 'row',
          justifyContent: 'space-between',
          alignItems: isMobile ? 'stretch' : 'center',
          gap: isMobile ? '0.75rem' : '0',
          padding: isMobile ? '16px' : '20px 1.5rem',
          background: themeColors.paginationBg,
          border: `1px solid ${themeColors.sectionBorder}`,
          borderRadius: '1rem'
        }}>
          <div style={{
            color: themeColors.textSecondary,
            fontSize: isMobile ? '0.8rem' : '0.9rem',
            textAlign: isMobile ? 'center' : 'left'
          }}>
            Página {currentPage} de {totalPages} • Total: {filteredCursos.length} cursos
          </div>
          <div style={{
            display: 'flex',
            gap: '0.5rem',
            flexWrap: 'wrap',
            justifyContent: isMobile ? 'center' : 'flex-start'
          }}>
            <button
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage === 1}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: isMobile ? '4px' : '0.375rem',
                padding: isMobile ? '8px 0.75rem' : '8px 1rem',
                background: currentPage === 1
                  ? (darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(241,245,249,0.85)')
                  : (darkMode ? 'rgba(255,255,255,0.1)' : '#ffffff'),
                border: `1px solid ${themeColors.controlBorder}`,
                borderRadius: '0.625rem',
                color: currentPage === 1 ? (darkMode ? 'rgba(255,255,255,0.3)' : 'rgba(148,163,184,0.85)') : themeColors.textPrimary,
                fontSize: isMobile ? '0.8rem' : '0.9rem',
                fontWeight: 600,
                cursor: currentPage === 1 ? 'not-allowed' : 'pointer',
                transition: 'all 0.2s ease',
                flex: isMobile ? '1' : 'initial'
              }}
            >
              <ChevronLeft size={isMobile ? 14 : 16} />
              {!isMobile && 'Anterior'}
            </button>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
              <button
                key={page}
                onClick={() => setCurrentPage(page)}
                style={{
                  padding: isMobile ? '8px 0.625rem' : '8px 0.875rem',
                  background: currentPage === page
                    ? 'linear-gradient(135deg, #ef4444, #dc2626)'
                    : (darkMode ? 'rgba(255,255,255,0.08)' : '#ffffff'),
                  border: currentPage === page
                    ? `1px solid ${darkMode ? '#ef4444' : '#dc2626'}`
                    : `1px solid ${themeColors.controlBorder}`,
                  borderRadius: '0.625rem',
                  color: currentPage === page ? '#fff' : themeColors.textPrimary,
                  fontSize: isMobile ? '0.8rem' : '0.9rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  transition: 'all 0.2s ease',
                  minWidth: isMobile ? '36px' : '2.5rem',
                }}
              >
                {page}
              </button>
            ))}
            <button
              onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
              disabled={currentPage === totalPages}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: isMobile ? '4px' : '0.375rem',
                padding: isMobile ? '8px 0.75rem' : '8px 1rem',
                background: currentPage === totalPages
                  ? (darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(241,245,249,0.85)')
                  : (darkMode ? 'rgba(255,255,255,0.1)' : '#ffffff'),
                border: `1px solid ${themeColors.controlBorder}`,
                borderRadius: '0.625rem',
                color: currentPage === totalPages ? (darkMode ? 'rgba(255,255,255,0.3)' : 'rgba(148,163,184,0.85)') : themeColors.textPrimary,
                fontSize: isMobile ? '0.8rem' : '0.9rem',
                fontWeight: 600,
                cursor: currentPage === totalPages ? 'not-allowed' : 'pointer',
                transition: 'all 0.2s ease',
                flex: isMobile ? '1' : 'initial'
              }}
            >
              {!isMobile && 'Siguiente'}
              <ChevronRight size={isMobile ? 14 : 16} />
            </button>
          </div>
        </div>
      )}

      {/* Modal */}
      {showModal && createPortal(
        <div
          className="modal-overlay"
          onClick={() => setShowModal(false)}
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            width: '100vw',
            height: '100vh',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 99999,
            padding: isMobile ? '1rem' : '2rem',
            backdropFilter: 'blur(8px)',
            background: 'rgba(0, 0, 0, 0.65)',
            overflowY: 'auto',
            overflowX: 'hidden',
            scrollBehavior: 'smooth'
          }}
        >
          <div
            className="modal-content"
            onClick={(e) => e.stopPropagation()}
            style={{
              position: 'relative',
              background: darkMode
                ? 'linear-gradient(135deg, rgba(0,0,0,0.9) 0%, rgba(26,26,46,0.9) 100%)'
                : 'linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(248,250,252,0.95) 100%)',
              border: '1px solid rgba(239, 68, 68, 0.2)',
              borderRadius: '12px',
              width: isMobile ? '92vw' : '70vw',
              maxWidth: isMobile ? '92vw' : '70vw',
              maxHeight: '85vh',
              padding: isMobile ? '0.75rem 0.875rem' : '1rem 1.5rem',
              margin: 'auto',
              color: darkMode ? '#fff' : '#1e293b',
              boxShadow: '0 20px 60px -12px rgba(0, 0, 0, 0.5)',
              overflowY: 'auto',
              overflowX: 'hidden',
              animation: 'scaleIn 0.3s ease-out'
            }}
          >
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: isMobile ? 12 : 14,
              paddingBottom: isMobile ? 8 : 10,
              borderBottom: '1px solid rgba(239, 68, 68, 0.2)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <BookOpen size={isMobile ? 18 : 20} style={{ color: '#ef4444' }} />
                <h3 style={{ margin: 0, fontSize: isMobile ? '0.95rem' : '1.05rem', fontWeight: '600', letterSpacing: '-0.01em', color: darkMode ? '#fff' : '#1e293b' }}>
                  {modalType === 'create' ? 'Nuevo Curso' : modalType === 'edit' ? 'Editar Curso' : 'Ver Curso'}
                </h3>
              </div>
              <button
                onClick={() => setShowModal(false)}
                style={{
                  background: darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
                  border: darkMode ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(0,0,0,0.15)',
                  borderRadius: '8px',
                  padding: '6px',
                  color: darkMode ? RedColorPalette.primaryLight : '#ef4444',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  transition: 'all 0.2s ease',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = 'rgba(239, 68, 68, 0.2)';
                  e.currentTarget.style.borderColor = 'rgba(239, 68, 68, 0.4)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = darkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)';
                  e.currentTarget.style.borderColor = darkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.15)';
                  e.currentTarget.style.color = darkMode ? RedColorPalette.primaryLight : '#ef4444';
                }}
              >
                <X size={16} color="currentColor" />
              </button>
            </div>

            <form onSubmit={handleSubmit}>
              <div style={{ display: 'grid', gridTemplateColumns: isSmallScreen ? '1fr' : '1fr 1fr', gap: isMobile ? '0.75rem' : '1rem', columnGap: isSmallScreen ? 0 : '1.25rem' }}>
                {/* Fila 1: Código y Tipo de curso */}
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Código</label>
                  <input
                    name="codigo_curso"
                    placeholder="Se genera automáticamente"
                    value={modalType === 'create' ? autoGeneratedCode : (modalType === 'edit' && autoGeneratedCode ? autoGeneratedCode : selectedCurso?.codigo_curso || '')}
                    required
                    disabled={modalType === 'view'}
                    readOnly={true}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? 'rgba(255,255,255,0.7)' : 'rgba(30,41,59,0.7)',
                      cursor: 'not-allowed',
                      fontSize: '0.8rem'
                    }}
                  />
                  <div style={{ marginTop: 6, color: darkMode ? 'rgba(255,255,255,0.55)' : 'rgba(30,41,59,0.6)', fontSize: '0.8rem' }}>Se genera automáticamente basado en el tipo de curso.</div>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Tipo de curso</label>
                  {modalType === 'edit' ? (
                    // En edición: mostrar solo el nombre del tipo (no editable)
                    <div style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b',
                      fontSize: '0.8rem',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem'
                    }}>
                      <span style={{
                        background: 'rgba(239, 68, 68, 0.15)',
                        color: '#ef4444',
                        padding: '2px 0.375rem',
                        borderRadius: '0.25rem',
                        fontSize: '0.7rem',
                        fontWeight: '600'
                      }}>
                        TIPO
                      </span>
                      {tiposCursos.find(tc => tc.id_tipo_curso === selectedCurso?.id_tipo_curso)?.nombre || `Tipo ID ${selectedCurso?.id_tipo_curso} (no encontrado)`}
                      <input
                        type="hidden"
                        name="id_tipo_curso"
                        value={selectedCurso?.id_tipo_curso || ''}
                      />
                    </div>
                  ) : (
                    // En creación: select normal
                    <StyledSelect
                      name="id_tipo_curso"
                      value={selectedTipoCurso || ''}
                      required
                      placeholder="Selecciona un tipo"
                      darkMode={darkMode}
                      style={{
                        padding: '0.75rem',
                        fontSize: '0.8rem'
                      }}
                      options={tiposCursos
                        .filter(tc => tc.estado === 'activo') // Solo tipos activos para crear cursos
                        .map(tc => ({ value: tc.id_tipo_curso, label: tc.nombre }))
                      }
                      onChange={handleTipoCursoChange}
                      disabled={modalType === 'view'}
                    />
                  )}
                  {modalType === 'edit' && (
                    <div style={{ marginTop: 6, color: darkMode ? 'rgba(255,255,255,0.55)' : 'rgba(30,41,59,0.6)', fontSize: '0.8rem' }}>
                      El tipo de curso no se puede cambiar en edición.
                    </div>
                  )}
                </div>

                {/* Fila 2: Nombre (izquierda) y Capacidad (derecha) */}
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Nombre</label>
                  <input
                    name="nombre"
                    placeholder={modalType === 'create' ? "Selecciona un tipo de curso primero" : "Nombre del curso"}
                    defaultValue={modalType === 'edit' ? selectedCurso?.nombre : ''}
                    value={modalType === 'create' ? autoGeneratedName : undefined}
                    required
                    disabled={modalType === 'view'}
                    readOnly={modalType === 'create'}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode
                        ? (modalType === 'edit' ? 'rgba(255,255,255,0.1)' : 'rgba(255,255,255,0.06)')
                        : (modalType === 'edit' ? 'rgba(0,0,0,0.08)' : 'rgba(0,0,0,0.05)'),
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode
                        ? (modalType === 'edit' ? '#fff' : 'rgba(255,255,255,0.7)')
                        : (modalType === 'edit' ? '#1e293b' : 'rgba(30,41,59,0.7)'),
                      cursor: modalType === 'edit' ? 'text' : 'not-allowed',
                      fontSize: '0.8rem'
                    }}
                  />
                  <div style={{ marginTop: 6, color: darkMode ? 'rgba(255,255,255,0.55)' : 'rgba(30,41,59,0.6)', fontSize: '0.8rem' }}>
                    {modalType === 'create'
                      ? 'Se completa automáticamente con el nombre del tipo de curso.'
                      : 'Puedes editar el nombre del curso.'
                    }
                  </div>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Capacidad</label>
                  <input
                    type="number"
                    name="capacidad_maxima"
                    defaultValue={modalType === 'edit' ? selectedCurso?.capacidad_maxima : 20}
                    min={1}
                    required
                    disabled={modalType === 'view'}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? '#fff' : '#1e293b',
                      fontSize: '0.8rem'
                    }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Horario *</label>
                  <select
                    name="horario"
                    defaultValue={selectedCurso?.horario || 'matutino'}
                    required
                    disabled={modalType === 'view'}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? '#fff' : '#1e293b',
                      fontSize: '0.8rem',
                      cursor: modalType === 'view' ? 'not-allowed' : 'pointer'
                    }}
                  >
                    <option value="matutino" style={{ background: darkMode ? 'rgba(0,0,0,0.9)' : '#fff', color: darkMode ? '#fff' : '#1e293b' }}>Matutino</option>
                    <option value="vespertino" style={{ background: darkMode ? 'rgba(0,0,0,0.9)' : '#fff', color: darkMode ? '#fff' : '#1e293b' }}>Vespertino</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Fecha Inicio</label>
                  <input
                    type="date"
                    name="fecha_inicio"
                    defaultValue={selectedCurso?.fecha_inicio || ''}
                    required
                    disabled={modalType === 'view'}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? '#fff' : '#1e293b',
                      fontSize: '0.8rem'
                    }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Fecha Fin</label>
                  <input
                    type="date"
                    name="fecha_fin"
                    defaultValue={selectedCurso?.fecha_fin || ''}
                    required
                    disabled={modalType === 'view'}
                    style={{
                      width: '100%',
                      padding: '0.75rem',
                      background: darkMode ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: '0.625rem',
                      color: darkMode ? '#fff' : '#1e293b',
                      fontSize: '0.8rem'
                    }}
                  />
                </div>
                {/* Fila extra: Estado a lo ancho para mantener tamaños de fecha iguales */}
                <div style={{ gridColumn: '1 / -1' }}>
                  <label style={{ display: 'block', marginBottom: 6, color: darkMode ? 'rgba(255,255,255,0.9)' : '#1e293b', fontWeight: 600, fontSize: '0.8rem' }}>Estado</label>
                  <StyledSelect
                    name="estado"
                    defaultValue={selectedCurso?.estado || 'activo'}
                    disabled={modalType === 'create'}
                    darkMode={darkMode}
                    style={{
                      padding: '0.75rem',
                      fontSize: '0.8rem'
                    }}
                    options={[
                      { value: 'activo', label: 'Activo' },
                      { value: 'finalizado', label: 'Finalizado' },
                      { value: 'cancelado', label: 'Cancelado' },
                    ]}
                  />
                </div>
                {/* Separador final */}
                <div style={{ gridColumn: '1 / -1', height: 1, background: 'rgba(255,255,255,0.1)', marginTop: 8 }} />
              </div>

              {modalType !== 'view' && (
                <div style={{ display: 'flex', flexDirection: isSmallScreen ? 'column-reverse' : 'row', gap: isMobile ? '10px' : '0.75rem', marginTop: isMobile ? '16px' : '2rem', justifyContent: 'flex-end' }}>
                  <button
                    type="button"
                    onClick={() => setShowModal(false)}
                    style={{
                      padding: isMobile ? '10px 1rem' : '0.75rem 1.5rem',
                      background: darkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.05)',
                      border: darkMode ? '1px solid rgba(255,255,255,0.2)' : '1px solid rgba(0,0,0,0.15)',
                      borderRadius: isMobile ? 10 : 12,
                      color: darkMode ? 'rgba(255,255,255,0.7)' : 'rgba(30,41,59,0.8)',
                      cursor: 'pointer',
                      fontSize: isMobile ? '0.9rem' : '1rem',
                      width: isSmallScreen ? '100%' : 'auto'
                    }}
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '0.5rem',
                      padding: isMobile ? '10px 1rem' : '0.75rem 1.5rem',
                      background: 'linear-gradient(135deg, #ef4444, #dc2626)',
                      border: 'none',
                      borderRadius: isMobile ? 10 : 12,
                      color: '#fff',
                      fontWeight: '600',
                      cursor: 'pointer',
                      fontSize: isMobile ? '0.9rem' : '1rem',
                      width: isSmallScreen ? '100%' : 'auto'
                    }}
                  >
                    <Save size={16} />
                    {modalType === 'create' ? 'Crear Curso' : 'Guardar Cambios'}
                  </button>
                </div>
              )}
            </form>
          </div>

          {/* Animaciones CSS */}
          <style>{`
            @keyframes slideUp {
              from {
                opacity: 0;
                transform: translateY(100%);
              }
              to {
                opacity: 1;
                transform: translateY(0);
              }
            }
            
            @keyframes scaleIn {
              from {
                opacity: 0;
                transform: scale(0.9);
              }
              to {
                opacity: 1;
                transform: scale(1);
              }
            }
          `}</style>
        </div>,
        document.body
      )}

      <DeleteCourseModal
        show={showDeleteModal}
        curso={cursoToDelete}
        darkMode={darkMode}
        isProcessing={deletingCurso}
        onCancel={closeDeleteModal}
        onConfirm={handleDeleteCurso}
      />

    </div>
  );
};

interface DeleteCourseModalProps {
  show: boolean;
  curso: Course | null;
  darkMode: boolean;
  isProcessing: boolean;
  onCancel: () => void;
  onConfirm: () => void;
}

function DeleteCourseModal({
  show,
  curso,
  darkMode,
  isProcessing,
  onCancel,
  onConfirm
}: DeleteCourseModalProps) {
  if (!show || !curso) return null;

  const overlayBackground = darkMode ? 'rgba(8, 8, 12, 0.75)' : 'rgba(15, 23, 42, 0.45)';
  const modalBackground = darkMode
    ? 'linear-gradient(135deg, rgba(10,10,18,0.96) 0%, rgba(34,34,48,0.96) 100%)'
    : 'linear-gradient(135deg, rgba(255,255,255,0.97) 0%, rgba(254,242,242,0.97) 100%)';
  const modalBorder = darkMode ? 'rgba(239, 68, 68, 0.25)' : 'rgba(248, 113, 113, 0.5)';
  const subtleText = darkMode ? 'rgba(226, 232, 240, 0.85)' : 'rgba(71, 85, 105, 0.9)';
  const accentColor = darkMode ? '#fca5a5' : '#dc2626';
  const accentSoft = darkMode ? 'rgba(248, 113, 113, 0.18)' : 'rgba(254, 215, 215, 0.85)';

  return createPortal(
    <div
      onClick={onCancel}
      style={{
        position: 'fixed',
        inset: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '1.25rem',
        zIndex: 100000,
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        background: overlayBackground
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          width: 'min(28rem, 92vw)',
          borderRadius: '1rem',
          background: modalBackground,
          border: `1px solid ${modalBorder}`,
          boxShadow: '0 28px 48px -18px rgba(15, 23, 42, 0.45)',
          padding: '1.75rem',
          color: darkMode ? '#fff' : '#1f2937',
          animation: 'scaleIn 0.3s ease-out'
        }}
      >
        <div
          style={{
            width: '3rem',
            height: '3rem',
            borderRadius: '0.9rem',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: accentSoft,
            border: `1px solid ${accentColor}33`,
            marginBottom: '1rem'
          }}
        >
          <Trash2 size={20} color={accentColor} strokeWidth={2.5} />
        </div>
        <h3 style={{ margin: '0 0 0.75rem 0', fontSize: '1.25rem', fontWeight: 700 }}>
          Confirmar eliminación
        </h3>
        <p style={{ margin: '0 0 1.5rem 0', fontSize: '0.95rem', color: subtleText, lineHeight: 1.6 }}>
          ¿Seguro que deseas eliminar el curso <strong style={{ color: accentColor }}>{curso.nombre}</strong>{' '}
          {curso.codigo_curso ? `(${curso.codigo_curso})` : ''}? Esta acción no se puede deshacer.
        </p>
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
          <button
            type="button"
            onClick={onCancel}
            style={{
              flex: '1 1 45%',
              padding: '0.75rem 1rem',
              borderRadius: '0.75rem',
              border: darkMode ? '1px solid rgba(255,255,255,0.15)' : '1px solid rgba(203,213,225,0.7)',
              background: darkMode ? 'rgba(255,255,255,0.06)' : '#fff',
              color: darkMode ? '#e2e8f0' : '#1f2937',
              fontWeight: 600,
              cursor: 'pointer',
              transition: 'all 0.2s ease'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = darkMode ? 'rgba(255,255,255,0.12)' : 'rgba(248,250,252,0.75)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = darkMode ? 'rgba(255,255,255,0.06)' : '#fff';
            }}
          >
            Cancelar
          </button>
          <button
            type="button"
            onClick={onConfirm}
            disabled={isProcessing}
            style={{
              flex: '1 1 45%',
              padding: '0.75rem 1rem',
              borderRadius: '0.75rem',
              border: 'none',
              background: 'linear-gradient(135deg, #ef4444, #dc2626)',
              color: '#fff',
              fontWeight: 700,
              cursor: isProcessing ? 'not-allowed' : 'pointer',
              opacity: isProcessing ? 0.8 : 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '0.5rem',
              transition: 'all 0.2s ease'
            }}
          >
            {isProcessing ? 'Eliminando...' : 'Eliminar'}
          </button>
        </div>

        <style>{`
          @keyframes scaleIn {
            from { opacity: 0; transform: scale(0.92); }
            to { opacity: 1; transform: scale(1); }
          }
        `}</style>
      </div>
    </div>,
    document.body
  );
}

export default GestionCursos;



